/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    id("java")
    id("application")
}

group = "brickBreaker"
version = "1.0.0"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    // No test dependencies
}

application {
    mainClass.set("brickBreaker.MainClass") // Ensure correct package path
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
